name: Test

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2

      - name: rustup
        run: rustup update

      - name: unit test
        run: cargo test

      - name: format
        run: cargo fmt --check
